version: "3.8"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - $DOCKER_USER_DIR/.data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    networks:
      - backend

  book-api:
    depends_on:
      - mongodb
    build:
      context: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend

  book-ui:
    depends_on:
      - book-api
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - $WEBAPP_LOCAL_PORT:$WEBAPP_DOCKER_PORT
    networks:
      - frontend

volumes:
  db:


networks:
  backend:
  frontend:
